spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Dgsmy111828
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最  大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证语句
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    # 从连接池获取连接时,是否检测连接可用性
    testOnBorrow: false
    # 释放连接到连接池时,是否检测连接可用性
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    # psCache缓存 100
    maxOpenPreparedStatements: 100
    maxPoolPreparedStatementPerConnectionSize: 50
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 对于建立连接过长的连接强制关闭
    removeAbandoned: true
    # 如果连接建立时间超过了30分钟，则强制将其关闭
    removeAbandonedTimeout: 1800
    # 将当前关闭动作记录到日志
    logAbandoned: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
#  velocity:
#    charset: UTF-8
#    properties:
#      input:
#        encoding: UTF-8
#      output:
#        encoding: UTF-8
#    resourceLoaderPath: classpath:/templates/
#    suffix: .vm
#    dateToolAttribute: dateTool
#  thymeleaf:
#    cache: false
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html
mybatis:
  # 指定*Mapper.xml的位置
  mapperLocations: classpath:mapper/*.xml
  # 指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名
  typeAliasesPackage: com.gao.mybatis.domain
  # configLocation: classpath:/mybatis-config.xml
security:
  basic:
    enabled: false
  ignored: /css/**
management:
  security:
   enabled: false
application:
  message: Hello Phil
